---
- name: Install WordPress, MariaDB, httpd, and PHP
  hosts: wordpress-server
  remote_user: root
  # remote_user: user
  # sudo: yes

  roles:
    - mountvol
    - referpkg
    - common
    - mariadb
    - httpd
    - php
    - wordpress
