---
- name: Install WordPress, MariaDB, httpd, and PHP
  hosts: WMHP
  remote_user: root
  # remote_user: user
  # sudo: yes

  roles:
    - referpkg
    - common
    - mariadb
    - httpd
    - php
    - wordpress
