---
- name: Install NFS-UTILS package for Client Server
  yum: name=nfs-utils state=present

- name: Update fstab file for mysql
  lineinfile:
    path: /etc/fstab
    line: "{{ address }}:/{{ volname1 }} /var/lib/mysql nfs defaults 0 0"
- name: Update fstab file for wordpress
  lineinfile:
    path: /etc/fstab
    line: "{{ address }}:/{{ volname2 }} /var/www/html nfs defaults 0 0"
- name: Verify mount directory exists for mysql data
  file:
    path: /var/lib/mysql
    state: directory
- name: Verify mount directory exists for wordpress core file
  file:
    path: /var/www/html
    state: directory
# - name: Mount nfs export for vol1
#    mount:
#      state: mounted
#      path: /var/lib/mysql
#      src: "{{ address }}:/{{ volname1 }}"
#      fstype: nfs
#  - name: Mount nfs export for vol2
#    mount:
#      state: mounted
#      path: /var/www/html
#      src: "{{ address }}:/{{ volname2 }}"
#      fstype: nfs
...
